# Generated by Django 3.0.7 on 2020-07-19 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='exit_door',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='app',
            field=models.CharField(choices=[('XIAOMI', 'Xiaomi'), ('LITTLELF', 'Littlelf'), ('ICSEE', 'iCSee'), ('HIKCONNECT', 'Hik-Connect')], max_length=20),
        ),
        migrations.AlterField(
            model_name='camera',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 19, 10, 52, 2, 564982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=models.CharField(choices=[('BEDROOM', 'Bedroom'), ('KITCHEN', 'Kitchen'), ('LIVING_ROOM', 'Living Room')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_link',
            field=models.URLField(),
        ),
    ]
