# Generated by Django 3.0.7 on 2020-07-20 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200719_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_reported',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 13, 53, 58, 926795, tzinfo=utc)),
        ),
    ]
