# Generated by Django 3.0.7 on 2020-07-22 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200722_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AlterField(
            model_name='camera',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 10, 2, 13, 260823, tzinfo=utc)),
        ),
    ]
