# Generated by Django 3.0.7 on 2020-07-22 10:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.functions.datetime
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200722_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 10, 21, 55, 577194, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now)], verbose_name='Timestamp'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(timestamp__lte=django.db.models.functions.datetime.Now()), name='event_timestamp_cannot_be_future_dated'),
        ),
    ]
