# Generated by Django 3.0.7 on 2020-08-09 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200722_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_visible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
